language: php

sudo: false
dist: trusty

notifications:
  email: false
  slack:
    secure: <secure token>

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules
    - "${TRAVIS_BUILD_DIR}/.plugin"
    - "${TRAVIS_BUILD_DIR}/.work/cache"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: prepare
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: deploy
    if: tag IS present

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh

    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-lint.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env: WP_VERSION=latest
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env: WP_VERSION=latest
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env:
        - WP_VERSION=5.1
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=5.0
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=4.9
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=3.9
      script: bash travis-ci/bin/php/wp-test.sh

    - stage: test
      language: node_js
      node_js: '10'
      dist: trusty
      script: bash travis-ci/bin/js/js-test.sh
    - stage: test
      language: node_js
      node_js: '11'
      dist: trusty
      env: COVERAGE_REPORT=1
      script: bash travis-ci/bin/js/js-test.sh


    - stage: prepare
      language: node_js
      node_js: '11'
      dist: trusty
      script:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/wp-check-diff.sh


    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/create.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        file: ${RELEASE_FILE}
        api_key:
          secure: <secure token>
        draft: true
        overwrite: true
        on:
          tags: true

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: bash travis-ci/bin/deploy/wp-release.sh
        on:
          tags: true

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      env:
        - GH_PAGES_PLUGIN_SCRIPT="./index.min.js"
        - GH_PAGES_PLUGIN_STYLE="./index.css"
        - GH_PAGES_TITLE="Test"
        - GH_PAGES_TEMPLATE=gutenberg
        - GH_PAGES_TRACKING_ID=UA-XXXXXXXX-X
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/gh-pages.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        keep_history: true
        local_dir: ${GH_PAGES_DIR}
        on:
          tags: true

  allow_failures:
    - env: WP_VERSION=4.9
    - env: WP_VERSION=3.9
